services:
  web:
    build: .
    working_dir: /code
    container_name: fastapi-items-example-web
    environment:
      FASTAPI_ENV: development
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
    volumes:
      - ./api/:/code/api/

  db:
    image: mysql:8.0
    container_name: fastapi-items-example-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastapi_items
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


networks:
  host:
    name: host
    external: true